# Generated by Django 5.0.6 on 2024-05-22 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('project_name',), 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='reference',
            options={'ordering': ('ref_name',), 'verbose_name': 'Reference', 'verbose_name_plural': 'References'},
        ),
        migrations.RemoveField(
            model_name='reference',
            name='ref_number',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='percentage',
        ),
        migrations.AddField(
            model_name='education',
            name='courses',
            field=models.TextField(blank=True, default='', verbose_name='Courses'),
        ),
        migrations.AddField(
            model_name='experience',
            name='job_description',
            field=models.TextField(blank=True, default='', verbose_name='Job Description'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_description',
            field=models.TextField(blank=True, default='', verbose_name='Project Description'),
        ),
        migrations.AddField(
            model_name='reference',
            name='ref_comment',
            field=models.TextField(blank=True, default='', verbose_name='Reference Comment'),
        ),
        migrations.AddField(
            model_name='reference',
            name='ref_email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Reference Email'),
        ),
        migrations.AddField(
            model_name='reference',
            name='ref_phone',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='Reference Phone'),
        ),
    ]
