# Generated by Django 5.0.6 on 2024-05-22 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_project_options_alter_reference_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={},
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_description',
        ),
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('Frontend Development', 'Frontend Development'), ('Backend Development', 'Backend Development'), ('Programming & Scripting', 'Programming & Scripting'), ('Professional & Soft Skills', 'Professional & Soft Skills')], default='Frontend Development', max_length=50, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='name',
            field=models.CharField(blank=True, default='', help_text='This is the variable of the setting.', max_length=254, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(blank=True, default='', help_text='This is the variable of the setting.', max_length=254, verbose_name='Name'),
        ),
    ]
